version: X0.{build}
skip_tags: true
image: Visual Studio 2017 Preview
shallow_clone: true
clone_folder: C:\Projects\PoE.Bot
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet publish --no-dependencies
artifacts:
- path: bin\Debug\netcoreapp2.1
  name: XO-2.1$(appveyor_build_version)